on: push
#on:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 0 * * *'
jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      - run: choco install gnuwin32-coreutils.install ninja nsis-unicode
      - run: choco install swig --version 3.0.8
      -
        name: Get revision and do the build
        run: ./build_llvm_package.bat "$(svn info https://llvm.org/svn/llvm-project/ | grep Revision | cut -d' ' -f2)" *>&1
        shell: powershell
