on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Install deps
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install gnuwin32-coreutils.install ninja nsis-unicode swig==3.0.8

      - run: svn info https://llvm.org/svn/llvm-project/ | grep Revision | cut -d' ' -f2 > revision.txt
      - run: set /p REVISION=<revision.txt
      - run: wget https://raw.githubusercontent.com/llvm/llvm-project/master/llvm/utils/release/build_llvm_package.bat
      - run: build_llvm_package.bat %REVISION%

